### ISSUE TITLE
Create initial architecture documentation for backend

### ISSUE THREAD

**Issue by aheil** [informatik-heilbronn/transparenz-cockpit#16]
For a quick ramp-up of new project members and contributrs, we should provide a sustainable documentation of the backend architecture.

As proposed a C4 model on level 3 would be suitable. 
- [x] Include C4 PlantUML as code in the repository (https://github.com/plantuml-stdlib/C4-PlantUML)
- [ ] Optional: Set up a pipeline that created C4 diagrams after a checkin/change of the diagram source files

**Comment by Faroesne** [comment]
First C4 PlantUML created and pushed in [c851526](https://github.com/informatik-heilbronn/transparenz-cockpit/commit/c8515267bf114dc7ae2fd16534884062c34a4b86)
Next step is set up the pipeline for creating C4 diagrams

**Comment by Faroesne** [comment]
Pipeline for generating svg files was created and finished with [3e6b8f4](https://github.com/informatik-heilbronn/transparenz-cockpit/commit/3e6b8f43a19c8e0339b96a17f3a920bafb809d21)
